config/routes.rb
Rails.application.routes.draw do
  root "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:create, :destroy], shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many  :doses, dependent: :destroy
  has_many  :ingredients, through: :doses
  validates :name, uniqueness: true, presence: :true
  validates :description, presence:  :true
  mount_uploader :photo, PhotoUploader
  after_destroy :destroy_photo

  private

  def destroy_photo
    puts "Photo à détruire (quand on pourra détruire les cocktails !)"
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to  :cocktail
  belongs_to  :ingredient
  validates   :description, presence: :true
  validates   :cocktail, uniqueness: { scope: :ingredient, message: "non non non" }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many  :doses
  has_many  :cocktails, through: :doses
  validates :name, uniqueness: true, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all.order(:name)
  end

  def new
    @cocktail = Cocktail.new
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @dose = Dose.new
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache, :description)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])

    @dose = @cocktail.doses.new(dose_params)
    if @dose.save
      redirect_to @cocktail
    else
      puts "dose pas sauvée!!!"
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input(:description) %>
  <%= f.hidden_field(:photo_cache) %>
  <%= f.file_field(:photo) %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/index.html.erb
<h1>Cocktails list</h1>

<ul class="list-group">
  <li class='list-group-item disabled'>
    <span class='name'>Cocktail name</span>
  </li>
  <% @cocktails.each do |cocktail| %>

<!--
  <a href="" class='list-group-item clearfix'>
    <span class='col-md-6'><%= link_to cocktail.name, cocktail_path(cocktail) %></span>
    <span class='col-md-6'><%= cocktail.ingredients.count.to_s %></span>
  </li>
 -->
<%= link_to cocktail_path(cocktail), class: 'list-group-item clearfix' do %>
  <span class='col-xs-5'><%= cocktail.name %></span>
  <span class='col-xs-3'><%= cocktail.ingredients.count.to_s %></span>
<% end %>



<!--   <li class='list-group-item'>
    <span class='name'><%= link_to cocktail.name, cocktail_path(cocktail) %></span>
    <span class='ingredients'><%= cocktail.ingredients.count.to_s %></span>
  </li>
 -->

  <% end %>
</ul>


<%#------- yield balise title -------%>
<% content_for(:title) do %>All the cocktails are on MisterCocktail<% end %>

<%#------- yield meta description -------%>
<% content_for(:description) do %>
All the cocktails are on MisterCocktail!
  <% if @cocktails.length > 10 %>
    Discover the
    <% c = @cocktails.to_a.shuffle.take(10) %>
    <% c.each do |c| %>
    <%= c.name %>,
    <% end %> and many more!
  <% end %>
<% end %>

app/views/cocktails/new.html.erb
<% content_for(:title) do %>
  Create a new cocktail on MisterCocktail
<% end %>

<h2>Add a cocktail</h2>

<%= render "form", cocktail: @cocktail %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<h4><%= @cocktail.description %></h4>
      <%= cl_image_tag @cocktail.photo.url(:bright_face) %>

      <hr>
      <%= render "doses/form", cocktail: @cocktail, dose: @dose %>

      <div class="row">
      <% @cocktail.doses.each do |dose| %>
      <% if !dose.id.nil? %>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('backgroundeuh.jpg');">
            <div class="card-category">Ingredient</div>
            <div class="card-description">
              <h2><%= dose.ingredient.name %></h2>
              <p><%= dose.description %></p>
              <%= link_to "&times;".html_safe, dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
      <% end %>
      </div>
<%#------- yield balise title -------%>
<% content_for(:title) do %><%= @cocktail.name %> on MisterCocktail<% end %>
<%#------- yield meta description -------%>
<% content_for(:description) do %>
The <%= @cocktail.name %> is on MisterCocktail : just add
  <% if @cocktail.ingredients.length > 1 %>
    <% a = @cocktail.ingredients.to_a.shuffle.take(3) %>
    <% a.each do |a| %>
      <% if !a.name.nil? %>
      <%= a.name %>,
      <% end %>
    <% end %> and maybe more!
  <% else %>
    <%= "a few ingredients..." %>
  <% end %>
<% end %>

app/views/doses/_form.html.erb
<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.association :ingredient %>
  <%= f.input :description %>

  <%= f.button :submit %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %><%= image_tag "logo.png" %><% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Button (call-to-action) -->
    <%= link_to "Create cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Create cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title).blank? ? "MisterCocktail" : yield(:title) %></title>
    <meta name="description" content="<%= (yield(:description) || '').squish %>">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
    <div class="navbar-wagon">
      <!-- Logo -->
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "logo.png" %>
      <% end %>
      <!-- Right Navigation -->
      <div class="navbar-wagon-right hidden-xs hidden-sm">
        <!-- Button (call-to-action) -->
        <%= link_to "Create cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
      </div>
      <!-- Dropdown list appearing on mobile only -->
      <div class="navbar-wagon-item hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Create cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %></li>
          </ul>
        </div>
      </div>
    </div>